on:
  workflow_dispatch:
  pull_request:

name: Upload VSIX
jobs:
  dryrun-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # 3.7.0
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'
          scope: '@openfga'
          always-auth: false
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - run: npm ci
      - run: npm install @vscode/vsce
      - run: npx vsce package -o openfga-latest.vsix
      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # 3.1.2
        with:
          name: openfga-latest.vsix
          if-no-files-found: error